# Zlib Module - Compression library
# Simple single-library module

[module]
name = "Zlib"
cmake_name = "ZLIB"
description = "A massively spiffy yet delicately unobtrusive compression library"
version = "1.2.11"

[resolution]
prefer = "jll"
fallback = ["system"]

# JLL Package Resolution
[jll]
package = "Zlib_jll"
auto_install = true

# Single component
[components]
zlib = { jll_export = "libz", required = true, description = "Zlib compression library" }

# System fallback
[system]
pkg_config = "zlib"
header_check = "zlib.h"
search_paths = ["/usr/lib", "/usr/local/lib"]

# Compiler/linker flags
[flags]
compile = []
link = []
defines = {}

# Version constraints
[version]
minimum = "1.2.0"
maximum = "1.99.99"
recommended = "1.2.11"

# Metadata
[metadata]
homepage = "https://www.zlib.net/"
documentation = "https://www.zlib.net/manual.html"
license = "Zlib"
