"""
MLIR thunk generation for STL container methods.

Generates MLIR IR that creates thunks for std::vector, std::string, etc.
Each thunk follows the FunctionGen.jl pattern:
  1. External declaration for the real C++ mangled symbol
  2. Thunk function with args_ptr interface + llvm.emit_c_interface

The thunks call real C++ methods via jlcs.ffe_call. Since the JIT is created
with shared_libs=[binary_path], it can resolve the mangled symbols at link time.
"""
module STLContainerGen

using ..TypeUtils

export generate_stl_thunks

# Method signatures: how many args (beyond 'this') and what MLIR types
# All methods receive 'this' as first arg (!llvm.ptr)
const STL_METHOD_SIGNATURES = Dict{String,NamedTuple{(:arg_types, :ret_type), Tuple{Vector{String}, String}}}(
    "constructor"  => (arg_types = String[],         ret_type = ""),
    "destructor"   => (arg_types = String[],         ret_type = ""),
    "size"         => (arg_types = String[],         ret_type = "i64"),
    "length"       => (arg_types = String[],         ret_type = "i64"),
    "capacity"     => (arg_types = String[],         ret_type = "i64"),
    "data"         => (arg_types = String[],         ret_type = "!llvm.ptr"),
    "push_back"    => (arg_types = ["!llvm.ptr"],    ret_type = ""),      # const T& -> ptr
    "subscript"    => (arg_types = ["i64"],           ret_type = "!llvm.ptr"),  # returns T&
    "at"           => (arg_types = ["i64"],           ret_type = "!llvm.ptr"),  # returns T&
    "clear"        => (arg_types = String[],         ret_type = ""),
    "reserve"      => (arg_types = ["i64"],           ret_type = ""),
    "resize"       => (arg_types = ["i64"],           ret_type = ""),
    "empty"        => (arg_types = String[],         ret_type = "i8"),    # bool -> i8
    "pop_back"     => (arg_types = String[],         ret_type = ""),
    "back"         => (arg_types = String[],         ret_type = "!llvm.ptr"),
    "front"        => (arg_types = String[],         ret_type = "!llvm.ptr"),
    "c_str"        => (arg_types = String[],         ret_type = "!llvm.ptr"),
    "append"       => (arg_types = ["!llvm.ptr"],    ret_type = "!llvm.ptr"),  # returns basic_string&
    "erase"        => (arg_types = ["!llvm.ptr"],    ret_type = "!llvm.ptr"),  # iterator-based
    "find"         => (arg_types = ["!llvm.ptr"],    ret_type = "!llvm.ptr"),  # returns iterator
    "count"        => (arg_types = ["!llvm.ptr"],    ret_type = "i64"),
    "insert"       => (arg_types = ["!llvm.ptr", "!llvm.ptr"], ret_type = "!llvm.ptr"),
    # Map-specific: keys passed by const reference (ptr), not integer index
    "map_at"       => (arg_types = ["!llvm.ptr"],    ret_type = "!llvm.ptr"),  # at(const K&) -> V&
    "map_subscript"=> (arg_types = ["!llvm.ptr"],    ret_type = "!llvm.ptr"),  # operator[](const K&) -> V&
)

"""
    generate_stl_thunks(stl_methods::Dict, metadata::Dict) -> String

Generate MLIR IR for STL container accessor thunks.

`stl_methods` maps container type (e.g., "std::vector<int>") to a vector
of method info dicts, each with "mangled", "method", "is_const" keys.
"""
function generate_stl_thunks(stl_methods::Dict, metadata::Dict=Dict())::String
    io = IOBuffer()
    println(io, "// STL Container Accessor Thunks")
    println(io, "// Auto-generated by RepliBuild STLContainerGen")
    println(io, "")

    generated = Set{String}()

    for (container_type, methods) in stl_methods
        println(io, "// --- $container_type ---")

        for method_info in methods
            mangled = get(method_info, "mangled", "")
            method_name = get(method_info, "method", "")

            isempty(mangled) && continue
            isempty(method_name) && continue

            # Skip if already generated (dedup)
            mangled in generated && continue
            push!(generated, mangled)

            # Look up the method signature
            if !haskey(STL_METHOD_SIGNATURES, method_name)
                continue
            end

            sig = STL_METHOD_SIGNATURES[method_name]

            # Build the full arg types list: this_ptr + method args
            all_arg_types = vcat(["!llvm.ptr"], sig.arg_types)
            ret_type = sig.ret_type

            # Format for MLIR
            args_str = join(all_arg_types, ", ")
            ext_ret = isempty(ret_type) ? "" : "-> $ret_type"
            thunk_ret = isempty(ret_type) ? "" : "-> $ret_type"

            # 1. External declaration
            println(io, "func.func private @$(mangled)($(args_str)) $ext_ret")

            # 2. Thunk function
            println(io, "func.func @$(mangled)_thunk(%args_ptr: !llvm.ptr) $thunk_ret attributes { llvm.emit_c_interface } {")

            # Load arguments from args_ptr
            call_args = String[]
            total_args = length(all_arg_types)

            for (i, mlir_t) in enumerate(all_arg_types)
                idx = i - 1
                println(io, "  %idx_$(i) = arith.constant $(idx) : i64")
                println(io, "  %arg_ptr_$(i) = llvm.getelementptr %args_ptr[%idx_$(i)] : (!llvm.ptr, i64) -> !llvm.ptr, !llvm.ptr")
                println(io, "  %val_ptr_$(i) = llvm.load %arg_ptr_$(i) : !llvm.ptr -> !llvm.ptr")

                if mlir_t == "!llvm.ptr"
                    # Pointer arg: dereference the pointer to get the actual pointer value
                    println(io, "  %val_$(i) = llvm.load %val_ptr_$(i) : !llvm.ptr -> !llvm.ptr")
                    push!(call_args, "%val_$(i)")
                elseif mlir_t == "i64"
                    # Integer arg: dereference the pointer to get the value
                    println(io, "  %val_$(i) = llvm.load %val_ptr_$(i) : !llvm.ptr -> i64")
                    push!(call_args, "%val_$(i)")
                elseif mlir_t == "i32"
                    println(io, "  %val_$(i) = llvm.load %val_ptr_$(i) : !llvm.ptr -> i32")
                    push!(call_args, "%val_$(i)")
                elseif mlir_t == "i8"
                    println(io, "  %val_$(i) = llvm.load %val_ptr_$(i) : !llvm.ptr -> i8")
                    push!(call_args, "%val_$(i)")
                else
                    # Fallback: treat as pointer
                    push!(call_args, "%val_ptr_$(i)")
                end
            end

            # Call using jlcs.ffe_call
            call_args_str = join(call_args, ", ")

            if isempty(ret_type)
                println(io, "  jlcs.ffe_call $call_args_str { callee = @$(mangled) } : ($(args_str)) -> ()")
                println(io, "  return")
            else
                println(io, "  %ret_val = jlcs.ffe_call $call_args_str { callee = @$(mangled) } : ($(args_str)) -> $ret_type")
                println(io, "  return %ret_val : $ret_type")
            end

            println(io, "}")
            println(io, "")
        end
    end

    return String(take!(io))
end

end # module STLContainerGen
